# Generated by Django 4.1.4 on 2022-12-29 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_subsubcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ('name',), 'verbose_name': 'Subcategory', 'verbose_name_plural': 'Subcategories'},
        ),
        migrations.AlterModelOptions(
            name='subsubcategory',
            options={'ordering': ('name',), 'verbose_name': 'Subsubcategory', 'verbose_name_plural': 'Subsubcategory'},
        ),
    ]
