# Generated by Django 4.1.4 on 2023-01-26 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_product_country_brand_slug_delete_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(default='', max_length=200, null=True, unique=True),
        ),
    ]
