# Generated by Django 4.1.4 on 2023-01-30 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.IntegerField(default=999999999, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='rating',
            field=models.IntegerField(default=999999999, null=True, unique=True),
        ),
    ]
