# Generated by Django 4.1.4 on 2023-01-30 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_product_rating_alter_image_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
