# Generated by Django 4.1.4 on 2023-01-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_image_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='rating',
            field=models.IntegerField(db_index=True, null=True, unique=True),
        ),
    ]
