# Generated by Django 4.1.4 on 2023-01-31 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_product_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='rating',
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
